/**
 * Kode permission yang dikenal aplikasi.
 * Source of truth: tabel Permission di database.
 * Constants ini hanya type-safe reference.
 */
export const PERMISSION_CODES = {
  DASHBOARD_VIEW: "DASHBOARD_VIEW",

  USER_VIEW: "USER_VIEW",
  USER_CREATE: "USER_CREATE",
  USER_UPDATE: "USER_UPDATE",
  USER_DELETE: "USER_DELETE",

  ROLE_VIEW: "ROLE_VIEW",
  ROLE_MANAGE: "ROLE_MANAGE",

  PRODUCT_VIEW: "PRODUCT_VIEW",
  PRODUCT_CREATE: "PRODUCT_CREATE",
  PRODUCT_UPDATE: "PRODUCT_UPDATE",
  PRODUCT_DELETE: "PRODUCT_DELETE",

  INVENTORY_VIEW: "INVENTORY_VIEW",
  INVENTORY_MANAGE: "INVENTORY_MANAGE",

  SALES_VIEW: "SALES_VIEW",
  SALES_CREATE: "SALES_CREATE",
  SALES_UPDATE: "SALES_UPDATE",

  PRODUCTION_VIEW: "PRODUCTION_VIEW",
  PRODUCTION_MANAGE: "PRODUCTION_MANAGE",

  PAYROLL_VIEW: "PAYROLL_VIEW",
  PAYROLL_MANAGE: "PAYROLL_MANAGE",

  REPORT_VIEW: "REPORT_VIEW",

  AUDIT_LOG_VIEW: "AUDIT_LOG_VIEW",

  // Keuangan Owner — SENSITIF (angka HPP/profit/margin hanya utk OWNER)
  HPP_VIEW: "HPP_VIEW",
  HPP_MANAGE: "HPP_MANAGE",
  PROFIT_VIEW: "PROFIT_VIEW",
  PROFIT_REPORT: "PROFIT_REPORT",
  MARGIN_VIEW: "MARGIN_VIEW",
  FINANCIAL_REPORT_VIEW: "FINANCIAL_REPORT_VIEW",
} as const;

export type PermissionCode =
  (typeof PERMISSION_CODES)[keyof typeof PERMISSION_CODES];
